//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch name can not be empty.
        /// </summary>
        internal static string Enitity_Branch_EmptyName {
            get {
                return ResourceManager.GetString("Enitity_Branch_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name can not be empty.
        /// </summary>
        internal static string Entity_Company_EmptyName {
            get {
                return ResourceManager.GetString("Entity_Company_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP can not be empty.
        /// </summary>
        internal static string Entity_Company_EmptyNip {
            get {
                return ResourceManager.GetString("Entity_Company_EmptyNip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON  can not be empty.
        /// </summary>
        internal static string Entity_Company_EmptyRegon {
            get {
                return ResourceManager.GetString("Entity_Company_EmptyRegon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency can not be empty.
        /// </summary>
        internal static string Entity_Offer_CurrencyIdRequired {
            get {
                return ResourceManager.GetString("Entity_Offer_CurrencyIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For inserting work range need insert Publication End .
        /// </summary>
        internal static string Entity_Offer_EmptyPublicationEndForWorkRange {
            get {
                return ResourceManager.GetString("Entity_Offer_EmptyPublicationEndForWorkRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary can not be less then zero.
        /// </summary>
        internal static string Entity_Offer_SalaryRangeLessZero {
            get {
                return ResourceManager.GetString("Entity_Offer_SalaryRangeLessZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Term can not be empty.
        /// </summary>
        internal static string Entity_Offer_SalaryTermIdRequired {
            get {
                return ResourceManager.GetString("Entity_Offer_SalaryTermIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work can be start minimum on next day after Publication End .
        /// </summary>
        internal static string Entity_Offer_WorkRangeLessPublicationEnd {
            get {
                return ResourceManager.GetString("Entity_Offer_WorkRangeLessPublicationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template description can not be empty.
        /// </summary>
        internal static string Entity_OfferTemplate_EmptyDescription {
            get {
                return ResourceManager.GetString("Entity_OfferTemplate_EmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name can not be empty.
        /// </summary>
        internal static string Entity_OfferTemplate_EmptyName {
            get {
                return ResourceManager.GetString("Entity_OfferTemplate_EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRS need to contain 10 numbers, value invalid.
        /// </summary>
        internal static string Record_Krs_Invalid {
            get {
                return ResourceManager.GetString("Record_Krs_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP need to contain 9 or 14 numbers, value invalid.
        /// </summary>
        internal static string Record_Nip_Invalid {
            get {
                return ResourceManager.GetString("Record_Nip_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON  need to contain 10 numbers, value invalid.
        /// </summary>
        internal static string Record_Regon_Invalid {
            get {
                return ResourceManager.GetString("Record_Regon_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This URL invalid.
        /// </summary>
        internal static string Record_Url_Invalid {
            get {
                return ResourceManager.GetString("Record_Url_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builder can not be completed because some properties not filled,.
        /// </summary>
        internal static string TemplateBuilder_IncompleteBuilding {
            get {
                return ResourceManager.GetString("TemplateBuilder_IncompleteBuilding", resourceCulture);
            }
        }
    }
}
