//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UseCase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UseCase.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains KRS duplicates existing company.
        /// </summary>
        internal static string Entity_Company_KrsDuplicate {
            get {
                return ResourceManager.GetString("Entity_Company_KrsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains Name duplicates existing company.
        /// </summary>
        internal static string Entity_Company_NameDuplicate {
            get {
                return ResourceManager.GetString("Entity_Company_NameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains NIP duplicates existing company.
        /// </summary>
        internal static string Entity_Company_NipDuplicate {
            get {
                return ResourceManager.GetString("Entity_Company_NipDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains REGON duplicates existing company.
        /// </summary>
        internal static string Entity_Company_RegonDuplicate {
            get {
                return ResourceManager.GetString("Entity_Company_RegonDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure_Address_Create_InvalidResult.
        /// </summary>
        internal static string Procedure_Address_Create_InvalidResult {
            get {
                return ResourceManager.GetString("Procedure_Address_Create_InvalidResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound Audience.
        /// </summary>
        internal static string UserSecrets_NotFound_Audience {
            get {
                return ResourceManager.GetString("UserSecrets_NotFound_Audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound Issuer.
        /// </summary>
        internal static string UserSecrets_NotFound_Issuer {
            get {
                return ResourceManager.GetString("UserSecrets_NotFound_Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound Kafka.
        /// </summary>
        internal static string UserSecrets_NotFound_Kafka {
            get {
                return ResourceManager.GetString("UserSecrets_NotFound_Kafka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound Redis.
        /// </summary>
        internal static string UserSecrets_NotFound_Redis {
            get {
                return ResourceManager.GetString("UserSecrets_NotFound_Redis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound RelationalDatabase.
        /// </summary>
        internal static string UserSecrets_NotFound_RelationalDatabase {
            get {
                return ResourceManager.GetString("UserSecrets_NotFound_RelationalDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound Secret.
        /// </summary>
        internal static string UserSecrets_NotFound_Secret {
            get {
                return ResourceManager.GetString("UserSecrets_NotFound_Secret", resourceCulture);
            }
        }
    }
}
